{{- range $key, $ing := .Values.ingresses }}
{{- if $ing.enabled }}
{{- $annotations := deepCopy ($ing.annotations | default dict) }}
{{- $mws := list }}
{{- if $.Values.noIndex.enabled }}
{{- $mws = append $mws (printf "%s-%s@kubernetescrd" $.Release.Namespace (include "tilleuls.noIndexName" $)) }}
{{- end }}
{{- if and $.Values.basicAuth.enabled (ne $ing.basicAuth false) }}
{{- $mws = append $mws (printf "%s-%s@kubernetescrd" $.Release.Namespace (include "tilleuls.basicAuthName" $)) }}
{{- end }}
{{- with get $annotations "traefik.ingress.kubernetes.io/router.middlewares" }}
{{- $mws = append $mws . }}
{{- end }}
{{- with $mws }}
{{- $_ := set $annotations "traefik.ingress.kubernetes.io/router.middlewares" (join "," .) }}
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "tilleuls.resourceName" (dict "root" $ "suffix" $key) }}
  labels:
    {{- include "tilleuls.labels" $ | nindent 4 }}
  {{- include "tilleuls.annotations" (dict "root" $ "annotations" $annotations) | nindent 2 }}
spec:
  {{- with $ing.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with $ing.tls }}
  tls:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  rules:
    {{- range $ing.hosts }}
    - host: {{ tpl .host $ | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "tilleuls.resourceName" (dict "root" $ "suffix" (.service | default "app")) }}
                port:
                  {{- $port := .port | default "http" }}
                  {{- if kindIs "string" $port }}
                  name: {{ $port }}
                  {{- else }}
                  number: {{ $port }}
                  {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}
