{{- range $key, $p := .Values.persistence }}
{{- if and $p.enabled (not $p.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tilleuls.resourceName" (dict "root" $ "suffix" $key) }}
  labels:
    {{- include "tilleuls.labels" $ | nindent 4 }}
  {{- include "tilleuls.annotations" (dict "root" $ "annotations" $p.annotations) | nindent 2 }}
spec:
  accessModes:
    {{- toYaml ($p.accessModes | default (list "ReadWriteOnce")) | nindent 4 }}
  {{- with $p.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ $p.size | default "1Gi" }}
{{- end }}
{{- end }}
