{{- with .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tilleuls.resourceName" (dict "root" $ "suffix" "env") }}
  labels:
    {{- include "tilleuls.labels" $ | nindent 4 }}
  {{- include "tilleuls.annotations" (dict "root" $) | nindent 2 }}
type: Opaque
stringData:
  {{- range $k, $v := . }}
  {{ $k }}: {{ tpl (toString $v) $ | quote }}
  {{- end }}
{{- end }}
