{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tilleuls.serviceAccountName" . }}
  labels:
    {{- include "tilleuls.labels" . | nindent 4 }}
  {{- include "tilleuls.annotations" (dict "root" . "annotations" .Values.serviceAccount.annotations) | nindent 2 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
